- name: create admin-user
  user:
    name: dmall
    system: yes

- name: Ensure the admin group exists
  ansible.builtin.group:
    name: wheel
    state: present

- name: Add the admin-user to the admin group
  ansible.builtin.user:
    name: dmall
    groups: wheel
    append: true # Ensures the user is added to the group without removing them from others

- name: create ansible-user
  user:
    name: ansible
    system: yes
